use_frameworks!

platform :ios, '9.0'

target 'MyFluterTest_Example' do
  pod 'MyFluterTest', :path => '../'

  target 'MyFluterTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
